CREATE TABLE IF NOT EXISTS "trades" (
  "id" text PRIMARY KEY NOT NULL,
  "source" text NOT NULL,
  "symbol" text NOT NULL,
  "base_asset" text NOT NULL,
  "quote_asset" text NOT NULL,
  "side" text NOT NULL,
  "qty" numeric(30, 10) NOT NULL,
  "price" numeric(30, 10) NOT NULL,
  "quote_qty" numeric(30, 10) NOT NULL,
  "commission" numeric(30, 10),
  "commission_asset" text,
  "executed_at" timestamp with time zone NOT NULL,
  "raw" jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS "movements" (
  "id" text PRIMARY KEY NOT NULL,
  "type" text NOT NULL,
  "asset" text NOT NULL,
  "amount" numeric(30, 10) NOT NULL,
  "fee" numeric(30, 10),
  "occurred_at" timestamp with time zone NOT NULL,
  "raw" jsonb,
  "metadata" jsonb
);
CREATE TABLE IF NOT EXISTS "realized_gains" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset" text NOT NULL,
  "qty" numeric(30, 10) NOT NULL,
  "acquisition_date" timestamp with time zone NOT NULL,
  "acquisition_cost_eur" numeric(30, 10) NOT NULL,
  "disposal_date" timestamp with time zone NOT NULL,
  "disposal_value_eur" numeric(30, 10) NOT NULL,
  "pnl_eur" numeric(30, 10) NOT NULL,
  "buy_source_id" text,
  "sell_source_id" text
);
CREATE TABLE IF NOT EXISTS "price_cache" (
  "asset" text NOT NULL,
  "quote" text NOT NULL,
  "minute" timestamp with time zone NOT NULL,
  "price" numeric(30, 10) NOT NULL,
  PRIMARY KEY("asset", "quote", "minute")
);
CREATE TABLE IF NOT EXISTS "ingestion_cursor" (
  "source" text NOT NULL,
  "symbol" text DEFAULT '' NOT NULL,
  "last_id" bigint,
  "last_sync_at" timestamp with time zone,
  PRIMARY KEY("source", "symbol")
);
CREATE TABLE IF NOT EXISTS "known_symbols" (
  "symbol" text PRIMARY KEY NOT NULL,
  "base_asset" text NOT NULL,
  "quote_asset" text NOT NULL,
  "first_seen_at" timestamp with time zone NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_trades_symbol_time" ON "trades" ("symbol", "executed_at");
CREATE INDEX IF NOT EXISTS "idx_trades_base_time" ON "trades" ("base_asset", "executed_at");
CREATE INDEX IF NOT EXISTS "idx_movements_asset_time" ON "movements" ("asset", "occurred_at");
CREATE INDEX IF NOT EXISTS "idx_movements_type_time" ON "movements" ("type", "occurred_at");
CREATE INDEX IF NOT EXISTS "idx_gains_disposal" ON "realized_gains" ("disposal_date");
CREATE INDEX IF NOT EXISTS "idx_gains_asset" ON "realized_gains" ("asset");
