CREATE TABLE IF NOT EXISTS "open_lots" (
  "asset" text NOT NULL,
  "source_id" text NOT NULL,
  "qty" numeric(30, 10) NOT NULL,
  "cost_per_unit_eur" numeric(30, 10) NOT NULL,
  "acquired_at" timestamp with time zone NOT NULL,
  "snapshot_at" timestamp with time zone NOT NULL,
  PRIMARY KEY("asset", "source_id")
);
CREATE INDEX IF NOT EXISTS "idx_open_lots_asset" ON "open_lots" ("asset");

CREATE TABLE IF NOT EXISTS "uncovered_disposals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset" text NOT NULL,
  "qty" numeric(30, 10) NOT NULL,
  "value_eur" numeric(30, 10),
  "occurred_at" timestamp with time zone NOT NULL,
  "source_id" text NOT NULL,
  "reason" text,
  "snapshot_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_uncovered_asset" ON "uncovered_disposals" ("asset");
CREATE INDEX IF NOT EXISTS "idx_uncovered_occurred" ON "uncovered_disposals" ("occurred_at");
